"""Migration

Revision ID: 726f8e03e73a
Revises: 
Create Date: 2025-12-10 10:15:43.897033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726f8e03e73a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_title', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.Enum('booked', 'window', 'blocked', 'completed', 'leave', name='event_type_enum'), nullable=False),
    sa.Column('visit_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('rooms',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('room_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('staff_number', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('staff_number')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('no_show', sa.Boolean(), nullable=True),
    sa.Column('out_of_window', sa.Boolean(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('users')
    op.drop_table('rooms')
    op.drop_table('event')
    # ### end Alembic commands ###
