"""initial migration

Revision ID: 8b3ba104ea40
Revises: 
Create Date: 2025-12-11 10:53:30.843003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3ba104ea40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('out_of_window', sa.Boolean(), nullable=True))
        batch_op.alter_column('note',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('out_of_window')

    # ### end Alembic commands ###
